# Example issue taken from: https://docs.taiga.io/api.html#object-issue-detail-list
issue_detail = {
    "assigned_to": None,
    "assigned_to_extra_info": None,
    "attachments": [],
    "blocked_note": "",
    "created_date": "2016-08-04T11:08:19Z",
    "due_date": None,
    "due_date_reason": "",
    "due_date_status": "not_set",
    "external_reference": None,
    "finished_date": None,
    "id": 114,
    "is_blocked": False,
    "is_closed": False,
    "is_voter": False,
    "is_watcher": False,
    "milestone": None,
    "modified_date": "2016-08-04T11:08:19Z",
    "owner": 13,
    "owner_extra_info": {
        "big_photo": None,
        "full_name_display": "Mohamed Ortega",
        "gravatar_id": "6d7e702bd6c6fc568fca7577f9ca8c55",
        "id": 13,
        "is_active": True,
        "photo": None,
        "username": "user7",
    },
    "priority": 23,
    "project": 8,
    "project_extra_info": {
        "id": 8,
        "logo_small_url": None,
        "name": "Project Example",
        "slug": "project-example",
    },
    "ref": 59,
    "severity": 38,
    "status": 58,
    "status_extra_info": {"color": "#666666", "is_closed": False, "name": "Postponed"},
    "subject": "Exception is thrown if trying to add a folder with existing name",
    "tags": [
        ["Cat", None],
        ["Dog", "#ae6519"],
    ],
    "total_voters": 0,
    "total_watchers": 1,
    "type": 23,
    "version": 1,
    "watchers": [13],
}

# Example story taken from: https://docs.taiga.io/api.html#object-userstory-detail-list
story_detail = {
    "assigned_to": None,
    "assigned_to_extra_info": None,
    "assigned_users": [],
    "attachments": [],
    "backlog_order": 2,
    "blocked_note": "",
    "client_requirement": False,
    "comment": "",
    "created_date": "2020-07-03T08:40:37.245Z",
    "due_date": None,
    "due_date_reason": "",
    "due_date_status": "not_set",
    "epic_order": None,
    "epics": None,
    "external_reference": None,
    "finish_date": None,
    "generated_from_issue": None,
    "generated_from_task": None,
    "id": 142,
    "is_blocked": False,
    "is_closed": False,
    "is_voter": False,
    "is_watcher": False,
    "kanban_order": 37,
    "milestone": None,
    "milestone_name": None,
    "milestone_slug": None,
    "modified_date": "2020-07-03T08:40:37.249Z",
    "origin_issue": None,
    "origin_task": None,
    "owner": 6,
    "owner_extra_info": {
        "big_photo": None,
        "full_name_display": "Vanesa Torres",
        "gravatar_id": "b579f05d7d36f4588b11887093e4ce44",
        "id": 6,
        "is_active": True,
        "photo": None,
        "username": "user2114747470430251528",
    },
    "points": {"1": 4, "2": 3, "3": 2, "4": 1, "43": 1, "44": 1},
    "project": 1,
    "project_extra_info": {
        "id": 1,
        "logo_small_url": None,
        "name": "Project Example 0",
        "slug": "project-0",
    },
    "ref": 79,
    "sprint_order": 2,
    "status": 2,
    "status_extra_info": {"color": "#ff8a84", "is_closed": False, "name": "Ready"},
    "subject": "Customer personal data",
    "tags": [["service catalog", None], ["customer", None]],
    "tasks": [],
    "team_requirement": False,
    "total_attachments": 0,
    "total_comments": 0,
    "total_points": 1.5,
    "total_voters": 0,
    "total_watchers": 0,
    "tribe_gig": None,
    "version": 1,
    "watchers": [],
}
