from util import misc


def test_valid_phone_number():
    """Test phone number validation"""

    # Numbers have been generated by Copilot

    # Test valid phone numbers
    assert misc.valid_phone_number("0412345678") == True
    assert misc.valid_phone_number("0412 345 678") == True
    assert misc.valid_phone_number("0412-345-678") == True
    assert misc.valid_phone_number("0412.345.678") == True
    assert misc.valid_phone_number("+61434957453") == True
    assert misc.valid_phone_number("08 9757 7453") == True
    assert misc.valid_phone_number("9757-7453") == True
    assert misc.valid_phone_number("482918231") == True

    # Test invalid phone numbers
    assert misc.valid_phone_number("08-9757-745") == False
    assert misc.valid_phone_number("045 67") == False
    assert misc.valid_phone_number("000") == False
    assert misc.valid_phone_number("1223a") == False
    assert misc.valid_phone_number("12345678901234567890") == False
    assert misc.valid_phone_number("N/A") == False
